"""
Station Map Renderer - Shows global map with fog of war.
Engine-owned. Students do NOT edit this file.
"""

# Room positions on a text-based grid
# Each room has coordinates (row, col) for positioning
ROOM_CONFIG = {
    "command_deck": {"abbrev": "CMD", "row": 0, "col": 1},
    "research_archive": {"abbrev": "ARC", "row": 2, "col": 0},
    "control_hub": {"abbrev": "CTRL", "row": 2, "col": 1},
    "medical_bay": {"abbrev": "MED", "row": 2, "col": 2},
    "crew_quarters": {"abbrev": "CRW", "row": 4, "col": 1},
    "engineering": {"abbrev": "ENG", "row": 6, "col": 0},
    "main_corridor": {"abbrev": "CORR", "row": 6, "col": 1},
    "lab_bench": {"abbrev": "LAB", "row": 6, "col": 2},
    "storage_cage": {"abbrev": "STO", "row": 8, "col": 1},
    "airlock": {"abbrev": "AIR", "row": 10, "col": 1},
}

# Connections between rooms (for drawing connectors)
# Format: (room1, room2, door_id or None if always open)
CONNECTIONS = [
    ("command_deck", "control_hub", "command_door"),  # Locked initially
    ("control_hub", "research_archive", None),  # Always open
    ("control_hub", "medical_bay", None),  # Always open
    ("control_hub", "crew_quarters", None),  # Always open
    ("crew_quarters", "main_corridor", None),  # Always open
    ("main_corridor", "engineering", None),  # Always open
    ("main_corridor", "research_lab", "security_door"),  # Locked initially
    ("main_corridor", "storage_cage", None),  # Always open
    ("storage_cage", "airlock", None),  # Always open
]


def render_station_map(current_room: str, visited_rooms: set, unlocked_doors: set) -> str:
    """
    Render the full station map with fog of war.
    
    Args:
        current_room: The room the player is currently in
        visited_rooms: Set of room IDs the player has visited
        unlocked_doors: Set of door IDs that have been unlocked
        
    Returns:
        ASCII art string of the station map
    """
    
    def get_room_display(room_id: str) -> str:
        """Get display text for a room box."""
        if room_id == current_room:
            return "[X]"
        elif room_id in visited_rooms:
            return ROOM_CONFIG[room_id]["abbrev"]
        else:
            return "???"
    
    def is_door_locked(door_id: str) -> bool:
        """Check if a door is still locked."""
        if door_id is None:
            return False
        return door_id not in unlocked_doors
    
    # Build the map line by line
    lines = []
    
    # Row 0: Command Deck
    cmd = get_room_display("command_deck")
    lines.append(f"              ┌─────┐")
    lines.append(f"              │ {cmd:^3} │")
    
    # Connector to Control Hub (potentially locked)
    cmd_door_locked = is_door_locked("command_door")
    if cmd_door_locked:
        lines.append(f"              └══╤══┘")
        lines.append(f"                 ║")
    else:
        lines.append(f"              └──┬──┘")
        lines.append(f"                 │")
    
    # Row 2: ARC - CTRL - MED
    arc = get_room_display("research_archive")
    ctrl = get_room_display("control_hub")
    med = get_room_display("medical_bay")
    
    if cmd_door_locked:
        lines.append(f"  ┌─────┐   ┌────╨────┐   ┌─────┐")
    else:
        lines.append(f"  ┌─────┐   ┌────┴────┐   ┌─────┐")
    lines.append(f"  │ {arc:^3} ├───┤  {ctrl:^4}  ├───┤ {med:^3} │")
    lines.append(f"  └─────┘   └────┬────┘   └─────┘")
    lines.append(f"                 │")
    
    # Row 4: Crew Quarters
    crw = get_room_display("crew_quarters")
    lines.append(f"              ┌──┴──┐")
    lines.append(f"              │ {crw:^3} │")
    lines.append(f"              └──┬──┘")
    lines.append(f"                 │")
    
    # Row 6: ENG - CORR - LAB
    eng = get_room_display("engineering")
    corr = get_room_display("main_corridor")
    lab = get_room_display("research_lab")
    lab_door_locked = is_door_locked("security_door")
    
    lines.append(f"  ┌─────┐   ┌────┴────┐   ┌─────┐")
    if lab_door_locked:
        lines.append(f"  │ {eng:^3} ├───┤  {corr:^4}  ├═══┤ {lab:^3} │")
    else:
        lines.append(f"  │ {eng:^3} ├───┤  {corr:^4}  ├───┤ {lab:^3} │")
    lines.append(f"  └─────┘   └────┬────┘   └─────┘")
    lines.append(f"                 │")
    
    # Row 8: Storage Cage
    sto = get_room_display("storage_cage")
    lines.append(f"              ┌──┴──┐")
    lines.append(f"              │ {sto:^3} │")
    lines.append(f"              └──┬──┘")
    lines.append(f"                 │")
    
    # Row 10: Airlock
    air = get_room_display("airlock")
    lines.append(f"              ┌──┴──┐")
    lines.append(f"              │ {air:^3} │")
    lines.append(f"              └─────┘")
    
    return "\n".join(lines)


def show_station_map(current_room: str, visited_rooms: set, unlocked_doors: set):
    """Display the station map."""
    print()
    print(render_station_map(current_room, visited_rooms, unlocked_doors))
    print()
