"""
Encounter System - Handles combat encounters.

Engine-owned. Students do NOT edit this file.
The engine calls student-built methods (choose_action, compute_damage) but handles the loop.
"""

import random


class Encounter:
    """Represents a single combat encounter."""
    
    def __init__(self, encounter_data: dict):
        """
        Initialize an encounter from content data.
        
        Args:
            encounter_data: Dict from encounters.json
        """
        self.id = encounter_data.get("id")
        self.name = encounter_data.get("name")
        self.description = encounter_data.get("description")
        self.intro_text = encounter_data.get("intro_text")
        self.victory_text = encounter_data.get("victory_text")
        self.defeat_text = encounter_data.get("defeat_text")
        
        self.max_health = encounter_data.get("health", 50)
        self.health = self.max_health
        self.damage = encounter_data.get("damage", 10)
        self.armour = encounter_data.get("armour", 0)
        
        self.attack_pattern = encounter_data.get("attack_pattern", ["attack"])
        self.pattern_index = 0
        
        self.attack_messages = encounter_data.get("attack_messages", ["The enemy attacks!"])
        self.defend_messages = encounter_data.get("defend_messages", ["The enemy defends."])
        
        self.is_final_boss = encounter_data.get("is_final_boss", False)
        self.is_defeated = False
        self.is_defending = False
    
    def get_next_action(self) -> str:
        """Get the enemy's next action based on attack pattern."""
        action = self.attack_pattern[self.pattern_index]
        self.pattern_index = (self.pattern_index + 1) % len(self.attack_pattern)
        return action
    
    def get_attack_message(self) -> str:
        """Get a random attack message."""
        return random.choice(self.attack_messages)
    
    def get_defend_message(self) -> str:
        """Get a random defend message."""
        if self.defend_messages:
            return random.choice(self.defend_messages)
        return f"The {self.name} braces itself."
    
    def take_damage(self, amount: int) -> int:
        """
        Apply damage to the enemy.
        
        Args:
            amount: Raw damage before armour.
            
        Returns:
            Actual damage dealt after armour.
        """
        # Apply armour reduction (halved if defending)
        effective_armour = self.armour * 2 if self.is_defending else self.armour
        actual_damage = max(0, amount - effective_armour)
        
        self.health = max(0, self.health - actual_damage)
        self.is_defending = False
        
        if self.health <= 0:
            self.is_defeated = True
        
        return actual_damage
    
    def defend(self):
        """Set the enemy to defending state."""
        self.is_defending = True


class EncounterManager:
    """Manages combat encounters using the engine loop."""
    
    # Combat options presented to player
    OPTIONS = ["Attack", "Defend", "Use Item", "Run"]
    
    def __init__(self, world_loader):
        """
        Initialize the encounter manager.
        
        Args:
            world_loader: WorldLoader instance for encounter data.
        """
        self.world_loader = world_loader
        self.defeated_encounters = set()
    
    def is_defeated(self, encounter_id: str) -> bool:
        """Check if an encounter has already been defeated."""
        return encounter_id in self.defeated_encounters
    
    def run_encounter(self, encounter_id: str, player) -> str:
        """
        Run a full encounter loop.
        
        Args:
            encounter_id: ID of the encounter to run.
            player: Player object (with choose_action, compute_damage, take_damage, heal).
            
        Returns:
            Result string: "victory", "defeat", or "escaped"
        """
        # Get encounter data
        encounter_data = self.world_loader.get_encounter(encounter_id)
        if not encounter_data:
            return "error"
        
        # Check if already defeated
        if encounter_id in self.defeated_encounters:
            return "already_defeated"
        
        # Create encounter instance
        enemy = Encounter(encounter_data)
        
        # Show intro
        print()
        print("=" * 60)
        print(enemy.intro_text)
        print("=" * 60)
        print()
        
        player_defending = False
        stim_boost = 0  # Temporary damage boost from stim
        
        # Combat loop
        while player.health > 0 and enemy.health > 0:
            # Show status
            print(f"\n--- {enemy.name}: {enemy.health}/{enemy.max_health} HP | You: {player.health}/{player.max_health} HP ---")
            
            # Player chooses action
            print("\nWhat do you do?")
            for i, option in enumerate(self.OPTIONS):
                print(f"  {i + 1}. {option}")
            
            # Get player choice via student method
            try:
                choice_index = player.choose_action(self.OPTIONS)
                if not isinstance(choice_index, int) or choice_index < 0 or choice_index >= len(self.OPTIONS):
                    print("Invalid choice - defaulting to Attack")
                    choice_index = 0
            except Exception as e:
                print(f"Error in choose_action: {e} - defaulting to Attack")
                choice_index = 0
            
            chosen_action = self.OPTIONS[choice_index]
            print(f"\nYou choose: {chosen_action}")
            
            # Process player action
            if chosen_action == "Attack":
                # Calculate damage using student method
                base_damage = 15 + stim_boost  # Base player damage + any stim boost
                if hasattr(player, 'accuracy'):
                    # Hit check based on accuracy
                    if random.randint(1, 100) > player.accuracy:
                        print("Your attack misses!")
                        damage_dealt = 0
                    else:
                        damage_dealt = player.compute_damage(base_damage, enemy.armour if not enemy.is_defending else enemy.armour * 2)
                        print(f"You strike the {enemy.name} for {damage_dealt} damage!")
                else:
                    damage_dealt = player.compute_damage(base_damage, enemy.armour)
                    print(f"You strike the {enemy.name} for {damage_dealt} damage!")
                
                if damage_dealt > 0:
                    enemy.take_damage(damage_dealt + enemy.armour)  # Re-add armour since take_damage applies it again
                player_defending = False
                stim_boost = 0  # Stim wears off after attacking
                
            elif chosen_action == "Defend":
                print("You raise your guard, bracing for the next attack.")
                player_defending = True
                
            elif chosen_action == "Use Item":
                print("(Item use in combat - simplified: healing items heal, stim boosts next attack)")
                # Check for healing items
                if player.inventory.has_item("med_patch"):
                    player.inventory.consume("med_patch")
                    player.heal(20)
                    print("You apply a Med Patch! +20 HP")
                elif player.inventory.has_item("med_kit"):
                    player.inventory.consume("med_kit")
                    player.heal(50)
                    print("You use the Medical Kit! +50 HP")
                elif player.inventory.has_item("stim_pack"):
                    player.inventory.consume("stim_pack")
                    stim_boost = 10
                    print("You inject the Stim Pack! +10 damage on next attack!")
                elif player.inventory.has_item("shield_plate"):
                    player.inventory.consume("shield_plate")
                    if hasattr(player, 'armour'):
                        player.armour += 15
                    print("You attach the Shield Plate! +15 armour!")
                else:
                    print("You don't have any usable items!")
                player_defending = False
                
            elif chosen_action == "Run":
                # Can only run from non-boss encounters
                if enemy.is_final_boss:
                    print("There's nowhere to run. The Security Chief blocks all exits.")
                else:
                    if random.random() < 0.5:
                        print("You manage to escape!")
                        return "escaped"
                    else:
                        print("You try to run but the enemy blocks your path!")
                player_defending = False
            
            # Check if enemy is defeated
            if enemy.health <= 0:
                break
            
            # Enemy turn
            enemy_action = enemy.get_next_action()
            
            if enemy_action == "attack":
                # Enemy attacks
                print(f"\n{enemy.get_attack_message()}")
                
                # Calculate damage to player
                effective_armour = (player.armour if hasattr(player, 'armour') else 0)
                if player_defending:
                    effective_armour *= 2
                    print("Your defensive stance absorbs some of the blow!")
                
                damage_to_player = player.compute_damage(enemy.damage, effective_armour)
                player.take_damage(damage_to_player + effective_armour)  # Offset armour double-application
                print(f"You take {damage_to_player} damage!")
                
            elif enemy_action == "defend":
                print(f"\n{enemy.get_defend_message()}")
                enemy.defend()
        
        # Determine outcome
        if player.health <= 0:
            print()
            print("=" * 60)
            print(enemy.defeat_text)
            print("=" * 60)
            return "defeat"
        else:
            print()
            print("=" * 60)
            print(enemy.victory_text)
            print("=" * 60)
            self.defeated_encounters.add(encounter_id)
            return "victory"
