"""
Learning summary display for post-level reflection.

Engine-owned. Students do NOT edit this file.
"""


def show_level_a_summary(player, damage_taken, healed, dodged=False):
    """
    Show what the student learned in Level A.
    
    Args:
        player: The Player object
        damage_taken: Total damage taken during gameplay
        healed: Amount healed
        dodged: Whether player successfully dodged debris
    """
    print()
    print("=" * 50)
    print("  📚 LEARNING SUMMARY")
    print("=" * 50)
    print()
    print("You just used YOUR Player class to:")
    print()
    print(f"  1. CREATE an object:")
    print(f"       player = Player('{player.name}')")
    print()
    print(f"  2. READ attributes:")
    print(f"       player.name → '{player.name}'")
    print(f"       player.health → {player.health}")
    print(f"       player.max_health → {player.max_health}")
    print()
    print(f"  3. CALL methods:")
    print(f"       player.get_status()")
    print(f"       player.take_damage({damage_taken})")
    print(f"       player.heal({healed})")
    print()
    print("-" * 50)
    print("  KEY OOP CONCEPTS PRACTICED")
    print("-" * 50)
    print()
    print("  ✓ Constructor (__init__)")
    print("      → Sets up the object's initial state")
    print()
    print("  ✓ Instance Attributes (self.name, self.health, ...)")
    print("      → Each object has its OWN copy of these values")
    print()
    print("  ✓ Methods")
    print("      → Functions that belong to the class")
    print("      → Can read AND modify the object's state")
    print()
    print("  ✓ Defensive Programming")
    print("      → Health is CLAMPED between 0 and max_health")
    print("      → Prevents invalid game states")
    print()
    
    if dodged:
        print("-" * 50)
        print("  🎮 BONUS: You successfully dodged the debris!")
        print("      Your quick reflexes reduced incoming damage.")
        print()
    
    print("=" * 50)
    print("  Next: Run validate.py for full automated checks")
    print("=" * 50)
    print()
