"""
Save/Load System - Handles game persistence.

Engine-owned. Students do NOT edit this file.
The engine calls student-built methods (to_save_data, from_save_data) for player serialisation.
"""

import json
import os
from pathlib import Path
from importlib import import_module


class SaveLoadManager:
    """Manages saving and loading game state."""
    
    def __init__(self, save_path: str = None):
        """
        Initialize the save/load manager.
        
        Args:
            save_path: Path to saves directory. Defaults to ./saves/
        """
        if save_path is None:
            save_path = Path(__file__).parent.parent / "saves"
        else:
            save_path = Path(save_path)
        
        self.save_path = save_path
        self.save_file = save_path / "game_save.json"
        
        # Ensure save directory exists
        self.save_path.mkdir(parents=True, exist_ok=True)
    
    def save_game(self, player, game_state: dict) -> bool:
        """
        Save the current game state.
        
        Args:
            player: Player object with to_save_data() method.
            game_state: Dict containing engine state (room, flags, etc.)
            
        Returns:
            True if save successful, False otherwise.
        """
        try:
            # Get player data via student method
            player_data = player.to_save_data()
            
            # Combine with engine state
            save_data = {
                "version": "1.0",
                "player": player_data,
                "engine_state": game_state
            }
            
            # Write to file
            with open(self.save_file, 'w', encoding='utf-8') as f:
                json.dump(save_data, f, indent=2)
            
            return True
            
        except Exception as e:
            print(f"Error saving game: {e}")
            return False
    
    def load_game(self, player_class) -> tuple:
        """
        Load a saved game state.
        
        Args:
            player_class: The Player class (or subclass) with from_save_data() classmethod.
            
        Returns:
            Tuple of (player_instance, engine_state) or (None, None) if load fails.
        """
        try:
            if not self.save_file.exists():
                print("No save file found.")
                return (None, None)
            
            # Read file
            with open(self.save_file, 'r', encoding='utf-8') as f:
                save_data = json.load(f)
            
            # Validate version
            if save_data.get("version") != "1.0":
                print("Save file version mismatch.")
                return (None, None)
            
            # Reconstruct player via student method
            player_data = save_data.get("player", {})
            player_type = player_data.get("player_type", "player").lower()
            resolved_class = self._resolve_player_class(player_type, player_class)
            
            if resolved_class is None:
                print("Could not determine player class for save file.")
                return (None, None)
            
            player = resolved_class.from_save_data(player_data)
            
            # Get engine state
            engine_state = save_data.get("engine_state", {})
            
            return (player, engine_state)
            
        except json.JSONDecodeError:
            print("Save file is corrupted.")
            return (None, None)
        except Exception as e:
            print(f"Error loading game: {e}")
            return (None, None)

    def _resolve_player_class(self, player_type: str, fallback_class):
        """Resolve the correct player class based on saved player_type."""
        class_map = {}
        
        for module_name in ("student.player_types", "student_reference.player_types"):
            try:
                module = import_module(module_name)
                brute_cls = getattr(module, "Brute", None)
                scout_cls = getattr(module, "Scout", None)
                if brute_cls:
                    class_map["brute"] = brute_cls
                if scout_cls:
                    class_map["scout"] = scout_cls
            except ImportError:
                continue
        
        for module_name in ("student.player", "student_reference.player"):
            try:
                module = import_module(module_name)
                player_cls = getattr(module, "Player", None)
                if player_cls:
                    class_map["player"] = player_cls
            except ImportError:
                continue
        
        return class_map.get(player_type, fallback_class)
    
    def has_save(self) -> bool:
        """Check if a save file exists."""
        return self.save_file.exists()
    
    def delete_save(self) -> bool:
        """Delete the save file."""
        try:
            if self.save_file.exists():
                self.save_file.unlink()
            return True
        except Exception:
            return False
