"""
Enhanced game loop for Level B - Character Specialisation with immersion.

This version adds:
  - Dramatic character selection
  - Side-by-side stat comparison
  - Combat simulation showing class differences
  - Learning summary

Engine-owned. Students do NOT edit this file.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from engine.immersion import (
    type_text, type_text_fast, dramatic_pause, 
    show_header, show_divider, prompt_choice, show_stat_comparison
)
from engine.learning_summary import show_level_b_summary


def main():
    """Enhanced Level B gameplay with immersion."""
    
    show_header("SIGMA-7 RESEARCH STATION", "Level B: Specialisation")
    
    # Import checks
    try:
        from student.player import Player
        from student.player_types import Brute, Scout
    except ImportError as e:
        print(f"Error: Could not import classes.")
        print(f"Make sure you've implemented Brute and Scout in student/player_types.py")
        print(f"Details: {e}")
        sys.exit(1)
    
    # === SCENE 1: SECURITY SCAN ===
    dramatic_pause(0.5)
    type_text("You step forward into the security checkpoint...")
    dramatic_pause(0.8)
    type_text("A laser grid sweeps over you from head to toe.")
    dramatic_pause(0.5)
    type_text_fast('  "Biometric analysis complete."')
    dramatic_pause(0.5)
    type_text_fast('  "Sector 7 survivors are assigned specialised roles."')
    print()
    
    # === CHARACTER SELECTION ===
    type_text("Three holographic profiles appear before you:")
    print()
    show_divider()
    print("  🔴 BRUTE")
    print("     Tank class. High health, heavy armour.")
    print("     Best for close combat. Reduced accuracy.")
    show_divider()
    print("  🔵 SCOUT")  
    print("     Precision class. Lower health, light armour.")
    print("     Exceptional accuracy. Strike targets reliably.")
    show_divider()
    print("  ⚪ STANDARD")
    print("     Balanced class. No particular specialisation.")
    print("     Jack of all trades.")
    show_divider()
    print()
    
    choice = prompt_choice([
        ('1', 'BRUTE (Tank)'),
        ('2', 'SCOUT (Precision)'),
        ('3', 'STANDARD (Balanced)'),
    ], "Select your specialisation:")
    
    print()
    name = input("Enter your name: ").strip() or "Unknown"
    
    # Create player
    if choice == '1':
        player = Brute(name)
        class_name = "Brute"
        type_text_fast(f'  "Survivor {name} registered as: BRUTE"')
    elif choice == '2':
        player = Scout(name)
        class_name = "Scout"
        type_text_fast(f'  "Survivor {name} registered as: SCOUT"')
    else:
        player = Player(name)
        class_name = "Player"
        type_text_fast(f'  "Survivor {name} registered as: STANDARD"')
    
    # === STAT COMPARISON ===
    dramatic_pause(1)
    print()
    type_text("The display shows a comparison of available profiles:")
    
    # Create instances for comparison
    try:
        base = Player("Standard")
        brute = Brute("Brute")
        scout = Scout("Scout")
        show_stat_comparison([base, brute, scout], ["Standard", "Brute", "Scout"])
    except Exception as e:
        print(f"Error comparing classes: {e}")
    
    # === COMBAT SIMULATION ===
    dramatic_pause(1)
    print()
    type_text_fast('  "Initiating combat readiness simulation..."')
    dramatic_pause(0.5)
    print()
    
    type_text("A holographic enemy appears!")
    print()
    
    # Simulate taking damage - demonstrates inherited method
    damage = 25
    print(f"The enemy strikes for {damage} damage...")
    player.take_damage(damage)
    print(f"  {player.get_status()}")
    
    if class_name == "Brute":
        type_text("Your high health absorbs the blow well!")
    elif class_name == "Scout":
        type_text("The hit stings - you need to avoid getting hit.")
    else:
        type_text("A solid hit, but you're still standing.")
    
    # Demonstrate healing
    dramatic_pause(0.8)
    print()
    type_text("You use a med-patch...")
    heal = 15
    player.heal(heal)
    print(f"  Healed {heal} HP. {player.get_status()}")
    
    # === FINALE ===
    dramatic_pause(1)
    print()
    show_divider("=")
    type_text_fast(f'  "Simulation complete. {class_name} profile confirmed."')
    type_text_fast('  "Proceed to equipment bay for inventory assignment."')
    show_divider("=")
    
    # === LEARNING SUMMARY ===
    dramatic_pause(1)
    show_level_b_summary(player, class_name, base)


if __name__ == "__main__":
    main()
