"""
Immersion utilities for enhanced Sigma-7 gameplay.

Engine-owned. Students do NOT edit this file.
"""

import time
import sys


def dramatic_pause(seconds=1.5):
    """Pause for dramatic effect."""
    time.sleep(seconds)


def type_text(text, delay=0.025):
    """Print text with typewriter effect."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def type_text_fast(text, delay=0.015):
    """Faster typewriter for longer text."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def countdown(message, seconds=3):
    """Show countdown with message."""
    for i in range(seconds, 0, -1):
        print(f"\r{message} {i}...", end='', flush=True)
        time.sleep(1)
    print()


def quick_time_event(prompt, success_keys=None, timeout=2.0):
    """
    Simple timed input challenge.
    Returns True if player responds correctly in time.
    """
    if success_keys is None:
        success_keys = ['d', 'dodge', 'roll']
    
    print()
    print(f"⚠️  {prompt}")
    print(f"    Quick! Type: {', '.join(success_keys)}")
    print()
    
    start = time.time()
    try:
        response = input(">>> ").strip().lower()
        elapsed = time.time() - start
        
        if elapsed > timeout:
            return False, elapsed
        return response in success_keys, elapsed
    except:
        return False, timeout


def show_divider(char="-", width=50):
    """Print a divider line."""
    print(char * width)


def show_header(title, subtitle=None):
    """Print a styled header."""
    print()
    print("=" * 50)
    print(f"  {title}")
    if subtitle:
        print(f"  {subtitle}")
    print("=" * 50)
    print()


def prompt_choice(options, prompt="Choose:"):
    """Show numbered options and get player choice."""
    print()
    for key, desc in options:
        print(f"  {key}. {desc}")
    print()
    
    valid_keys = [str(k) for k, _ in options]
    while True:
        choice = input(f"{prompt} ").strip()
        if choice in valid_keys:
            return choice
        print(f"Please enter one of: {', '.join(valid_keys)}")


def show_stat_comparison(players, labels):
    """Display side-by-side stat comparison for multiple players."""
    print()
    print("-" * 60)
    
    # Calculate column widths
    header = f"{'Stat':<12}"
    for label in labels:
        header += f"{label:>14}"
    print(header)
    print("-" * 60)
    
    stats = ['health', 'max_health', 'armour', 'accuracy']
    stat_labels = ['Health', 'Max Health', 'Armour', 'Accuracy']
    
    for stat, label in zip(stats, stat_labels):
        row = f"{label:<12}"
        for p in players:
            val = getattr(p, stat, 'N/A')
            if stat == 'accuracy':
                row += f"{val:>13}%"
            else:
                row += f"{val:>14}"
        print(row)
    
    print("-" * 60)
