"""
Learning summary display for Level B - Inheritance & Specialisation.

Engine-owned. Students do NOT edit this file.
"""


def show_level_b_summary(player, player_class_name, base_player):
    """
    Show what the student learned in Level B.
    
    Args:
        player: The player's chosen character
        player_class_name: Name of the class ('Brute', 'Scout', or 'Player')
        base_player: A base Player for comparison
    """
    print()
    print("=" * 50)
    print("  📚 LEARNING SUMMARY")
    print("=" * 50)
    print()
    print("You just used INHERITANCE to create specialised classes:")
    print()
    print("  BASE CLASS:")
    print(f"    Player → health=100, armour=2, accuracy=85")
    print()
    print("  SUBCLASSES (inherit from Player):")
    print(f"    Brute  → health=120, armour=3, accuracy=70")
    print(f"    Scout  → health=80, armour=1, accuracy=95")
    print()
    
    if player_class_name != 'Player':
        print(f"  Your {player_class_name} INHERITED:")
        print(f"    ✓ The name attribute")
        print(f"    ✓ get_status() method")
        print(f"    ✓ take_damage() method")
        print(f"    ✓ heal() method")
        print()
        print(f"  Your {player_class_name} OVERRODE:")
        print(f"    ✓ Starting stats (different health, armour, accuracy)")
        print(f"    ✓ describe_specialty() output (class-specific description)")
    
    print()
    print("-" * 50)
    print("  KEY OOP CONCEPTS PRACTICED")
    print("-" * 50)
    print()
    print("  ✓ Inheritance (class Brute(Player):)")
    print("      → Child class gains all parent's attributes/methods")
    print()
    print("  ✓ super().__init__(name)")
    print("      → Calls the parent's constructor")
    print("      → Sets up inherited attributes")
    print()
    print("  ✓ Polymorphism")
    print("      → Different classes, same interface")
    print("      → All can call get_status(), take_damage(), heal()")
    print()
    print("  ✓ Specialisation")
    print("      → Subclasses customise specific values")
    print("      → Brute trades accuracy for health")
    print("      → Scout trades health for accuracy")
    print()
    print("=" * 50)
    print("  Next: Run validate.py for full automated checks")
    print("=" * 50)
    print()
