"""
Enhanced game loop for Level A - tests Player class with immersion.

This version adds:
  - Typewriter text effects
  - Interactive dodge mechanic
  - Exploration choices
  - Learning summary

Engine-owned. Students do NOT edit this file.
"""

import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from engine.immersion import (
    type_text, type_text_fast, dramatic_pause, 
    quick_time_event, show_header, show_divider, prompt_choice
)
from engine.learning_summary import show_level_a_summary


def main():
    """Enhanced Level A gameplay with immersion."""
    
    show_header("SIGMA-7 RESEARCH STATION", "Level A: The Awakening")
    
    # Import check
    try:
        from student.player import Player
    except ImportError as e:
        print(f"Error: Could not import Player class.")
        print(f"Make sure you've implemented it in student/player.py")
        print(f"Details: {e}")
        sys.exit(1)
    
    # === SCENE 1: AWAKENING ===
    dramatic_pause(0.5)
    type_text("Emergency lights flicker overhead...")
    dramatic_pause(1)
    type_text("You gasp awake, disoriented. Cold metal beneath you.")
    dramatic_pause(0.8)
    type_text("The air tastes stale. Recycled. Station air.")
    dramatic_pause(1)
    print()
    type_text("A crackling voice breaks the silence:")
    dramatic_pause(0.5)
    type_text_fast('  "Survivor detected in Sector 7 airlock."')
    type_text_fast('  "Please identify yourself for station records."')
    print()
    
    # Get player name
    name = input("Enter your name: ").strip()
    if not name:
        name = "Unknown"
    
    # Create player - this tests their __init__
    try:
        player = Player(name)
    except Exception as e:
        print(f"\n❌ Error creating Player: {e}")
        print("Check your __init__ method in student/player.py")
        sys.exit(1)
    
    # Verify attributes exist
    required_attrs = ['name', 'health', 'max_health', 'armour', 'accuracy']
    for attr in required_attrs:
        if not hasattr(player, attr):
            print(f"\n❌ Error: Player missing '{attr}' attribute")
            print("Make sure you set self.{attr} in __init__")
            sys.exit(1)
    
    print()
    type_text_fast(f'  "Identity confirmed: {player.name}"')
    type_text_fast(f'  "Biometrics: Normal. Proceed with caution."')
    
    # === SCENE 2: EXPLORATION CHOICE ===
    dramatic_pause(1)
    print()
    type_text("You pull yourself to your feet and look around.")
    type_text("The airlock is small, dimly lit, with damage everywhere.")
    print()
    
    choice = prompt_choice([
        ('1', 'Examine the control panel'),
        ('2', 'Look at the viewing port'),
        ('3', 'Check yourself for injuries'),
    ], "What do you do?")
    
    print()
    if choice == '1':
        type_text("The control panel sparks weakly. Most systems are offline.")
        type_text("A status display shows: SECTION BREACH DETECTED.")
    elif choice == '2':
        type_text("Through the scratched porthole, you see stars.")
        type_text("And debris. Lots of debris. Something went very wrong.")
    else:
        type_text("You pat yourself down. No major injuries.")
        type_text("Just a headache and fragments of memory you can't piece together.")
    
    # Show status - tests get_status()
    print()
    show_divider()
    try:
        status = player.get_status()
        print(f"Status: {status}")
    except Exception as e:
        print(f"❌ Error calling get_status(): {e}")
        print("Check your get_status method.")
    show_divider()
    
    # === SCENE 3: DEBRIS EVENT (Quick-Time) ===
    dramatic_pause(1.5)
    print()
    type_text("CREAK... GROAN...")
    dramatic_pause(0.8)
    type_text("The ceiling shudders. Metal fatigue.")
    dramatic_pause(0.5)
    
    print()
    print("⚠️  A SUPPORT BEAM IS FALLING!")
    
    success, reaction_time = quick_time_event(
        "DODGE NOW!", 
        success_keys=['d', 'dodge', 'roll', 'duck', 'move'],
        timeout=2.5
    )
    
    # Calculate damage based on dodge success
    if success:
        damage = 5
        print()
        type_text("✓ You throw yourself sideways just in time!")
        type_text(f"  The beam clips your shoulder. Minor damage.")
    else:
        damage = 20
        print()
        type_text("✗ The beam catches you across the back!")
        type_text("  You stagger from the impact.")
    
    # Test take_damage
    try:
        player.take_damage(damage)
        print()
        print(f"You took {damage} damage. {player.get_status()}")
    except Exception as e:
        print(f"\n❌ Error calling take_damage(): {e}")
        print("Check your take_damage method.")
    
    total_damage = damage
    
    # === SCENE 4: RECOVERY (Healing) ===
    dramatic_pause(1)
    print()
    type_text("As the dust settles, you spot something on the floor...")
    type_text("A first aid kit! Standard station issue.")
    print()
    
    use_kit = prompt_choice([
        ('y', 'Use the first aid kit'),
        ('n', "Leave it (you're fine)"),
    ], "Use it?")
    
    heal_amount = 0
    if use_kit == 'y':
        heal_amount = 15
        print()
        type_text("You pop open the kit and apply the medical gel.")
        
        # Test heal
        try:
            player.heal(heal_amount)
            print()
            print(f"Healed {heal_amount} HP. {player.get_status()}")
        except Exception as e:
            print(f"\n❌ Error calling heal(): {e}")
            print("Check your heal method.")
    else:
        print()
        type_text("You leave the kit. Might need it later.")
    
    # === FINALE ===
    dramatic_pause(1)
    print()
    show_divider("=")
    type_text("The intercom crackles one last time:")
    type_text_fast(f'  "Survivor {player.name}, proceed to the main corridor."')
    type_text_fast('  "Good luck. You\'re going to need it."')
    show_divider("=")
    
    # === LEARNING SUMMARY ===
    dramatic_pause(1)
    show_level_a_summary(player, total_damage, heal_amount, dodged=success)


if __name__ == "__main__":
    main()
