"""
Immersion utilities for enhanced Sigma-7 gameplay.

Engine-owned. Students do NOT edit this file.
"""

import time
import sys


def dramatic_pause(seconds=1.5):
    """Pause for dramatic effect."""
    time.sleep(seconds)


def type_text(text, delay=0.025):
    """Print text with typewriter effect."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def type_text_fast(text, delay=0.015):
    """Faster typewriter for longer text."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def countdown(message, seconds=3):
    """Show countdown with message."""
    for i in range(seconds, 0, -1):
        print(f"\r{message} {i}...", end='', flush=True)
        time.sleep(1)
    print()


def quick_time_event(prompt, success_keys=None, timeout=2.0):
    """
    Simple timed input challenge.
    Returns True if player responds correctly in time.
    
    Args:
        prompt: The warning message to show
        success_keys: List of valid responses (default: ['d', 'dodge', 'roll'])
        timeout: Time limit in seconds
    
    Returns:
        Tuple of (success: bool, response_time: float)
    """
    if success_keys is None:
        success_keys = ['d', 'dodge', 'roll']
    
    print()
    print(f"⚠️  {prompt}")
    print(f"    Quick! Type: {', '.join(success_keys)}")
    print()
    
    start = time.time()
    try:
        response = input(">>> ").strip().lower()
        elapsed = time.time() - start
        
        if elapsed > timeout:
            return False, elapsed
        return response in success_keys, elapsed
    except:
        return False, timeout


def show_divider(char="-", width=50):
    """Print a divider line."""
    print(char * width)


def show_header(title, subtitle=None):
    """Print a styled header."""
    print()
    print("=" * 50)
    print(f"  {title}")
    if subtitle:
        print(f"  {subtitle}")
    print("=" * 50)
    print()


def prompt_choice(options, prompt="Choose:"):
    """
    Show numbered options and get player choice.
    
    Args:
        options: List of (key, description) tuples
        prompt: The prompt text
    
    Returns:
        The chosen key
    """
    print()
    for key, desc in options:
        print(f"  {key}. {desc}")
    print()
    
    valid_keys = [str(k) for k, _ in options]
    while True:
        choice = input(f"{prompt} ").strip()
        if choice in valid_keys:
            return choice
        print(f"Please enter one of: {', '.join(valid_keys)}")
