"""
Enhanced game loop for Level C - Inventory system with immersion.

This version adds:
  - Equipment bay scene
  - Interactive item collection
  - Inventory management decisions
  - Learning summary

Engine-owned. Students do NOT edit this file.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    """Enhanced Level C gameplay with immersion."""
    
    # Import immersion after path setup
    from engine.immersion import (
        type_text, type_text_fast, dramatic_pause,
        show_header, show_divider, prompt_choice, show_inventory_display
    )
    from engine.learning_summary import show_level_c_summary
    
    show_header("SIGMA-7 RESEARCH STATION", "Level C: Equipment Bay")
    
    # Import checks
    try:
        from student.player import Player
        from student.inventory import Inventory
    except ImportError as e:
        print(f"Error: Could not import classes.")
        print(f"Make sure you've implemented Inventory in student/inventory.py")
        print(f"Details: {e}")
        sys.exit(1)
    
    # Check for MAX_CAPACITY
    if not hasattr(Inventory, 'MAX_CAPACITY'):
        print("Error: Inventory class needs a MAX_CAPACITY class variable")
        sys.exit(1)
    
    # === SCENE 1: ENTERING EQUIPMENT BAY ===
    dramatic_pause(0.5)
    type_text("The door slides open with a pneumatic hiss...")
    dramatic_pause(0.8)
    type_text("You step into the station's equipment bay.")
    dramatic_pause(0.5)
    type_text("Emergency lighting casts long shadows across scattered gear.")
    print()
    
    # Get name and create player
    name = input("Enter your name: ").strip() or "Unknown"
    
    try:
        player = Player(name)
    except Exception as e:
        print(f"\n❌ Error creating Player: {e}")
        sys.exit(1)
    
    # Check player has inventory
    if not hasattr(player, 'inventory'):
        print("\n❌ Error: Player must have an 'inventory' attribute")
        print("   In Player.__init__, add: self.inventory = Inventory()")
        sys.exit(1)
    
    print()
    type_text_fast(f'  "Welcome, {player.name}. Equipment bay unlocked."')
    type_text_fast(f'  "Inventory capacity: {Inventory.MAX_CAPACITY} items."')
    
    # === SCENE 2: ITEM DISCOVERY ===
    dramatic_pause(1)
    print()
    type_text("Scanning the room, you spot several useful items...")
    print()
    
    available_items = [
        ("keycard", "A security keycard with a blue stripe"),
        ("crowbar", "A sturdy metal crowbar"),
        ("torch", "A battery-powered flashlight"),
        ("med_patch", "Emergency medical patch"),
        ("ration_pack", "Station survival rations"),
    ]
    
    # Track what was added/removed
    items_added = []
    items_removed = []
    
    # Interactive item collection
    for item_id, description in available_items:
        print()
        show_divider()
        print(f"  📦 {item_id.upper()}")
        print(f"     {description}")
        show_divider()
        
        if player.inventory.is_full():
            type_text("Your inventory is FULL!")
            choice = prompt_choice([
                ('d', 'Drop an item to make room'),
                ('s', 'Skip this item'),
            ], "What do you do?")
            
            if choice == 'd':
                # Show current items and let them drop one
                print()
                print("Current inventory:")
                current = player.inventory.list_items()
                for i, item in enumerate(current):
                    print(f"  {i+1}. {item}")
                
                drop_choice = input("Enter number to drop (or 's' to skip): ").strip()
                if drop_choice.isdigit():
                    idx = int(drop_choice) - 1
                    if 0 <= idx < len(current):
                        dropped = current[idx]
                        player.inventory.remove(dropped)
                        items_removed.append(dropped)
                        type_text(f"Dropped {dropped}.")
                    else:
                        type_text("Invalid choice. Skipping item.")
                        continue
                else:
                    type_text("Skipping item.")
                    continue
                    
                # Now try to add the new item
                if player.inventory.add(item_id):
                    items_added.append(item_id)
                    type_text(f"Picked up {item_id}!")
            else:
                type_text("Leaving item behind...")
        else:
            choice = prompt_choice([
                ('y', 'Pick it up'),
                ('n', 'Leave it'),
            ], f"Take the {item_id}?")
            
            if choice == 'y':
                if player.inventory.add(item_id):
                    items_added.append(item_id)
                    type_text(f"Added {item_id} to inventory.")
                else:
                    type_text("Couldn't add item!")
            else:
                type_text("You leave the item.")
    
    # === FINAL INVENTORY CHECK ===
    dramatic_pause(1)
    print()
    type_text("You've finished searching the equipment bay.")
    
    show_inventory_display(player.inventory)
    
    # Test has_item
    if player.inventory.has_item("keycard"):
        type_text("The keycard could open locked doors...")
    if player.inventory.has_item("med_patch"):
        type_text("That med_patch could save your life later.")
    
    # === FINALE ===
    dramatic_pause(1)
    print()
    show_divider("=")
    type_text_fast('  "Equipment phase complete."')
    type_text_fast('  "Proceed to cargo section for supply usage training."')
    show_divider("=")
    
    # === LEARNING SUMMARY ===
    dramatic_pause(1)
    show_level_c_summary(player, items_added, items_removed)


if __name__ == "__main__":
    main()
