"""
Immersion utilities for enhanced Sigma-7 gameplay.

Engine-owned. Students do NOT edit this file.
"""

import time
import sys


def dramatic_pause(seconds=1.5):
    """Pause for dramatic effect."""
    time.sleep(seconds)


def type_text(text, delay=0.025):
    """Print text with typewriter effect."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def type_text_fast(text, delay=0.015):
    """Faster typewriter for longer text."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def show_divider(char="-", width=50):
    """Print a divider line."""
    print(char * width)


def show_header(title, subtitle=None):
    """Print a styled header."""
    print()
    print("=" * 50)
    print(f"  {title}")
    if subtitle:
        print(f"  {subtitle}")
    print("=" * 50)
    print()


def prompt_choice(options, prompt="Choose:"):
    """Show numbered options and get player choice."""
    print()
    for key, desc in options:
        print(f"  {key}. {desc}")
    print()
    
    valid_keys = [str(k) for k, _ in options]
    while True:
        choice = input(f"{prompt} ").strip()
        if choice in valid_keys:
            return choice
        print(f"Please enter one of: {', '.join(valid_keys)}")


def show_inventory_display(inventory):
    """Nicely formatted inventory display."""
    # Get MAX_CAPACITY dynamically to avoid importing student code
    max_cap = getattr(inventory, 'MAX_CAPACITY', 5)
    if hasattr(inventory.__class__, 'MAX_CAPACITY'):
        max_cap = inventory.__class__.MAX_CAPACITY
    
    print()
    print("┌" + "─" * 38 + "┐")
    print("│          📦 INVENTORY              │")
    print("├" + "─" * 38 + "┤")
    
    items = inventory.list_items()
    if items:
        for item in items:
            padded = f"  {item}"[:36]
            print(f"│ {padded:<36} │")
    else:
        print("│           (empty)                   │")
    
    print("├" + "─" * 38 + "┤")
    print(f"│  Items: {inventory.count():>2} / {max_cap:<2}                      │")
    print("└" + "─" * 38 + "┘")
