"""
Game Loop - Main game controller and command handlers.

Engine-owned. Students do NOT edit this file.
"""

import sys
from .world_loader import WorldLoader
from .command_parser import CommandParser
from .encounter import EncounterManager
from .save_load import SaveLoadManager
from .immersion import (
    type_text, type_text_slow, type_text_fast, dramatic_pause,
    show_divider, movement_narration, npc_greeting, death_sequence,
    room_atmosphere, item_pickup_narration, ambient_flavor
)


class GameState:
    """Tracks mutable game state (unlocked doors, taken items, etc.)."""
    
    def __init__(self):
        self.current_room = "airlock"
        self.visited_rooms = set()
        self.taken_items = set()  # Items removed from world
        self.unlocked_doors = set()  # Door IDs that are unlocked
        self.opened_containers = set()  # Container IDs that are opened
        self.triggered_encounters = set()  # Encounters that have triggered
        self.npc_dialogue_state = {}  # NPC ID -> dialogue trigger state
        self.puzzle_solved = set()  # Puzzle IDs that are solved
        self.game_complete = False
    
    def to_dict(self) -> dict:
        """Convert state to serialisable dict."""
        return {
            "current_room": self.current_room,
            "visited_rooms": list(self.visited_rooms),
            "taken_items": list(self.taken_items),
            "unlocked_doors": list(self.unlocked_doors),
            "opened_containers": list(self.opened_containers),
            "triggered_encounters": list(self.triggered_encounters),
            "npc_dialogue_state": self.npc_dialogue_state,
            "puzzle_solved": list(self.puzzle_solved),
            "game_complete": self.game_complete
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "GameState":
        """Reconstruct state from dict."""
        state = cls()
        state.current_room = data.get("current_room", "airlock")
        state.visited_rooms = set(data.get("visited_rooms", []))
        state.taken_items = set(data.get("taken_items", []))
        state.unlocked_doors = set(data.get("unlocked_doors", []))
        state.opened_containers = set(data.get("opened_containers", []))
        state.triggered_encounters = set(data.get("triggered_encounters", []))
        state.npc_dialogue_state = data.get("npc_dialogue_state", {})
        state.puzzle_solved = set(data.get("puzzle_solved", []))
        state.game_complete = data.get("game_complete", False)
        return state


class Game:
    """Main game controller."""
    
    TITLE = """
╔═══════════════════════════════════════════════════════════════════╗
║                                                                   ║
║   ███████╗██╗ ██████╗ ███╗   ███╗ █████╗       ███████╗           ║
║   ██╔════╝██║██╔════╝ ████╗ ████║██╔══██╗      ╚════██║           ║
║   ███████╗██║██║  ███╗██╔████╔██║███████║█████╗    ██╔╝           ║
║   ╚════██║██║██║   ██║██║╚██╔╝██║██╔══██║╚════╝   ██╔╝            ║
║   ███████║██║╚██████╔╝██║ ╚═╝ ██║██║  ██║        ██║              ║
║   ╚══════╝╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝        ╚═╝              ║
║                                                                   ║
║                  R E S E A R C H   S T A T I O N                  ║
║                                                                   ║
║         An OOP Text Adventure Learning Experience                 ║
╚═══════════════════════════════════════════════════════════════════╝
"""
    
    INTRO = """
Three months ago, Sigma-7 Research Station went dark.

No distress calls. No automated reports. Nothing but silence from the 
orbital facility that housed humanity's most classified research 
programmes.

You were sent to investigate.

You don't remember the crash. You don't remember how you ended up in 
the emergency airlock. But you remember your mission: find out what 
happened, and get out alive.

The escape pod is offline. The station AI watches your every move.
And something in the shadows doesn't want you to leave.

Welcome to Sigma-7. Good luck.
"""
    
    def __init__(self):
        """Initialize the game."""
        self.world = WorldLoader()
        self.parser = CommandParser()
        self.encounters = EncounterManager(self.world)
        self.saves = SaveLoadManager()
        self.state = GameState()
        self.player = None
        self.running = False
        self.player_class = None  # Set during character creation
    
    def start(self):
        """Start the game."""
        print(self.TITLE)
        dramatic_pause(0.5)
        for line in self.INTRO.strip().split('\n'):
            if line.strip():
                type_text(line)
            else:
                print()
            dramatic_pause(0.1)
        print()
        
        # Check for existing save
        if self.saves.has_save():
            print("A saved game was found. Load it? (yes/no)")
            choice = input("> ").strip().lower()
            if choice in ("yes", "y"):
                self._load_game()
                if self.player:
                    self.running = True
                    self._game_loop()
                    return
        
        # Character creation
        self._create_character()
        
        # Show the starting room
        self.state.visited_rooms.add(self.state.current_room)
        self._describe_room()
        
        # Start main loop
        self.running = True
        self._game_loop()
    
    def _create_character(self):
        """Character creation sequence."""
        print("\n" + "=" * 60)
        print("CHARACTER CREATION")
        print("=" * 60)
        
        # Get name
        print("\nWhat is your name, survivor?")
        name = input("> ").strip()
        if not name:
            name = "Unknown Survivor"
        
        # Import player classes
        try:
            from student.player_types import Brute, Scout
            from student.player import Player
        except ImportError:
            print("Error: Could not load player classes from student/")
            sys.exit(1)
        
        # Choose class
        print(f"\nWelcome, {name}. Choose your background:")
        print("\n  1. BRUTE")
        print("     A heavy-combat specialist. High health and armour, ")
        print("     but lower accuracy. When you hit, you hit hard.")
        print("     [Health: 120 | Armour: 3 | Accuracy: 70%]")
        print("\n  2. SCOUT")
        print("     A reconnaissance expert. Lower health and armour,")
        print("     but excellent accuracy. Every shot counts.")
        print("     [Health: 80 | Armour: 1 | Accuracy: 95%]")
        
        while True:
            print("\nEnter 1 or 2:")
            choice = input("> ").strip()
            if choice == "1":
                self.player = Brute(name)
                self.player_class = Brute
                print(f"\nYou are {name}, the Brute. Built for survival.")
                break
            elif choice == "2":
                self.player = Scout(name)
                self.player_class = Scout
                print(f"\nYou are {name}, the Scout. Precision is your weapon.")
                break
            else:
                print("Please enter 1 or 2.")
        
        print("\n" + "-" * 60)
        input("Press Enter to begin...")
    
    def _game_loop(self):
        """Main game loop."""
        while self.running:
            if self.state.game_complete:
                self._show_victory()
                break
            
            print()
            raw = input("> ").strip()
            if not raw:
                continue
            
            parsed = self.parser.parse(raw)
            self._handle_command(parsed)
    
    def _handle_command(self, parsed: dict):
        """Route a parsed command to the appropriate handler."""
        cmd = parsed["command"]
        args = parsed["args"]
        
        if cmd is None:
            return
        
        if cmd == "unknown":
            self._unknown_command(args)
        elif cmd == "look":
            self._look_handler(args)
        elif cmd in ("north", "south", "east", "west", "up", "down"):
            self._move_handler([cmd])
        elif cmd == "move":
            self._move_handler(args)
        elif cmd == "take":
            self._take_handler(args)
        elif cmd == "inventory":
            self._inventory_handler(args)
        elif cmd == "use":
            self._use_handler(args)
        elif cmd == "talk":
            self._talk_handler(args)
        elif cmd == "status":
            self._status_handler(args)
        elif cmd == "save":
            self._save_handler(args)
        elif cmd == "load":
            self._load_handler(args)
        elif cmd == "help":
            self._help_handler(args)
        elif cmd == "quit":
            self._quit_handler(args)
        else:
            self._unknown_command([cmd] + args)
    
    def _unknown_command(self, args: list):
        """Handle unknown commands."""
        if args:
            print(f"I don't understand '{' '.join(args)}'. Type 'help' for commands.")
        else:
            print("I didn't catch that. Type 'help' for commands.")
    
    def _describe_room(self):
        """Describe the current room."""
        room = self.world.get_room(self.state.current_room)
        if not room:
            print("Error: Room not found.")
            return
        
        first_visit = self.state.current_room not in self.state.visited_rooms
        
        print()
        print("═" * 60)
        print(f"  ▸ {room['name'].upper()}")
        print("═" * 60)
        
        desc = room.get("description_first", room.get("description", "You are here."))
        if not first_visit and "description_revisit" in room:
            desc = room.get("description_revisit")
        
        # Typewriter effect for room descriptions
        if first_visit:
            type_text(desc)
        else:
            print(desc)
        
        self.state.visited_rooms.add(self.state.current_room)
        
        # Occasional ambient atmosphere
        room_atmosphere(room['name'], first_visit)
        
        # Show items (not taken)
        self._show_room_items()
        
        # Show NPCs
        self._show_room_npcs()
        
        # Show exits
        self._show_exits()
    
    def _show_room_items(self):
        """Show items in the current room."""
        room = self.world.get_room(self.state.current_room)
        if not room:
            return
        
        # Regular items
        for item_id in room.get("items", []):
            if item_id not in self.state.taken_items:
                item = self.world.get_item(item_id)
                if item:
                    desc = item.get('description_room')
                    if not desc:
                        desc = "You see a " + item.get('name', 'something') + "."
                    print("\n" + desc)
        
        # Hidden items (reveal if condition met)
        for item_id, hint in room.get("hidden_items", {}).items():
            if item_id not in self.state.taken_items:
                # Show hint for hidden items
                print(f"\n{hint}")
        
        # Container contents
        if "chest" in room:
            chest = room["chest"]
            if chest["id"] not in self.state.opened_containers:
                if chest.get("locked", False):
                    print(f"\nA heavy chest sits in the corner, its lock jammed shut.")
                else:
                    print(f"\nAn open chest reveals its contents.")
            else:
                # Show chest contents if not taken
                for item_id in chest.get("contains", []):
                    if item_id not in self.state.taken_items:
                        item = self.world.get_item(item_id)
                        if item:
                            print(f"\nIn the chest: {item.get('description_room')}")
    
    def _show_room_npcs(self):
        """Show NPCs in the current room."""
        room = self.world.get_room(self.state.current_room)
        if not room:
            return
        
        for npc_id in room.get("npcs", []):
            npc = self.world.get_npc(npc_id)
            if npc:
                print(f"\n{npc.get('description')}")
    
    def _show_exits(self):
        """Show available exits."""
        room = self.world.get_room(self.state.current_room)
        if not room:
            return
        
        exits = room.get("exits", {})
        locked = room.get("locked_exits", {})
        
        if exits:
            exit_strs = []
            for direction, dest in exits.items():
                if direction in locked and locked[direction] not in self.state.unlocked_doors:
                    exit_strs.append(f"{direction} (locked)")
                else:
                    exit_strs.append(direction)
            print(f"\nExits: {', '.join(exit_strs)}")
    
    def _look_handler(self, args: list):
        """Handle look command."""
        if not args:
            self._describe_room()
        else:
            target = " ".join(args)
            self._examine(target)
    
    def _examine(self, target: str):
        """Examine a specific thing."""
        target = target.lower()
        
        # Check inventory items
        for item_id in self.player.inventory.list_items():
            item = self.world.get_item(item_id)
            if item and (target in item_id.lower() or target in item.get("name", "").lower()):
                desc = item.get("description_examine")
                if not desc:
                    desc = "It's a " + item.get('name', 'something') + "."
                print(desc)
                return
        
        # Check room items
        room = self.world.get_room(self.state.current_room)
        if room:
            for item_id in room.get("items", []) + list(room.get("hidden_items", {}).keys()):
                if item_id not in self.state.taken_items:
                    item = self.world.get_item(item_id)
                    if item and (target in item_id.lower() or target in item.get("name", "").lower()):
                        desc = item.get("description_examine")
                        if not desc:
                            desc = "It's a " + item.get('name', 'something') + "."
                        print(desc)
                        return
            
            # Check NPCs
            for npc_id in room.get("npcs", []):
                npc = self.world.get_npc(npc_id)
                if npc and (target in npc_id.lower() or target in npc.get("name", "").lower()):
                    print(npc.get("description", f"You see {npc['name']}."))
                    return
        
        print(f"You don't see '{target}' here.")
    
    def _move_handler(self, args: list):
        """Handle movement."""
        if not args:
            print("Move where? (north, south, east, west, up, down)")
            return
        
        direction = self.parser.normalise_direction(args[0])
        room = self.world.get_room(self.state.current_room)
        
        if not room:
            return
        
        exits = room.get("exits", {})
        locked_exits = room.get("locked_exits", {})
        
        if direction not in exits:
            print("You can't go that way.")
            return
        
        # Check if locked
        if direction in locked_exits:
            door_id = locked_exits[direction]
            if door_id not in self.state.unlocked_doors:
                print("That way is locked.")
                return
        
        # Check for exit encounter trigger
        encounter_id = room.get("encounter_on_first_exit")
        if encounter_id and encounter_id not in self.state.triggered_encounters:
            self.state.triggered_encounters.add(encounter_id)
            result = self.encounters.run_encounter(encounter_id, self.player)
            if result == "defeat":
                self._handle_death()
                return
            elif result == "escaped":
                print("You retreat back into the room.")
                return
        
        # Move to new room
        movement_narration(direction)
        new_room_id = exits[direction]
        self.state.current_room = new_room_id
        
        # Check for entry encounter
        new_room = self.world.get_room(new_room_id)
        if new_room:
            encounter_id = new_room.get("encounter_on_first_entry")
            if encounter_id and encounter_id not in self.state.triggered_encounters:
                # Show room first
                self._describe_room()
                # Then trigger encounter
                self.state.triggered_encounters.add(encounter_id)
                result = self.encounters.run_encounter(encounter_id, self.player)
                if result == "defeat":
                    self._handle_death()
                    return
                return
        
        self._describe_room()
    
    def _take_handler(self, args: list):
        """Handle taking items."""
        if not args:
            print("Take what?")
            return
        
        target = " ".join(args).lower()
        room = self.world.get_room(self.state.current_room)
        
        if not room:
            return
        
        # Check regular items
        for item_id in room.get("items", []):
            if item_id not in self.state.taken_items:
                item = self.world.get_item(item_id)
                if item and (target in item_id.lower() or target in item.get("name", "").lower()):
                    if self.player.inventory.add(item_id):
                        self.state.taken_items.add(item_id)
                        item_pickup_narration(item['name'])
                    else:
                        print("Your inventory is full!")
                    return
        
        # Check hidden items
        for item_id in room.get("hidden_items", {}).keys():
            if item_id not in self.state.taken_items:
                item = self.world.get_item(item_id)
                if item and (target in item_id.lower() or target in item.get("name", "").lower()):
                    if self.player.inventory.add(item_id):
                        self.state.taken_items.add(item_id)
                        print(f"You find and take the {item['name']}!")
                    else:
                        print("Your inventory is full!")
                    return
        
        # Check chest contents
        if "chest" in room:
            chest = room["chest"]
            if chest["id"] in self.state.opened_containers:
                for item_id in chest.get("contains", []):
                    if item_id not in self.state.taken_items:
                        item = self.world.get_item(item_id)
                        if item and (target in item_id.lower() or target in item.get("name", "").lower()):
                            if self.player.inventory.add(item_id):
                                self.state.taken_items.add(item_id)
                                print(f"You take the {item['name']} from the chest.")
                            else:
                                print("Your inventory is full!")
                            return
        
        print(f"You don't see '{target}' to take.")
    
    def _inventory_handler(self, args: list):
        """Show inventory."""
        items = self.player.inventory.list_items()
        
        print("\n--- INVENTORY ---")
        if not items:
            print("  (empty)")
        else:
            for item_id in items:
                item = self.world.get_item(item_id)
                if item:
                    print(f"  • {item.get('description_inventory', item['name'])}")
        print(f"\nCapacity: {self.player.inventory.count()}/{self.player.inventory.MAX_CAPACITY}")
    
    def _use_handler(self, args: list):
        """Handle using items."""
        if not args:
            print("Use what?")
            return
        
        item_str, target_str = self.parser.parse_use_command(args)
        
        if not item_str:
            print("Use what?")
            return
        
        # Find the item in inventory
        found_item_id = None
        for item_id in self.player.inventory.list_items():
            item = self.world.get_item(item_id)
            if item and (item_str in item_id.lower() or item_str in item.get("name", "").lower()):
                found_item_id = item_id
                break
        
        if not found_item_id:
            print(f"You don't have '{item_str}'.")
            return
        
        # Get item data
        item = self.world.get_item(found_item_id)
        
        # Call student's use_item method
        try:
            result = self.player.use_item(found_item_id, target_str)
            print(result)
        except Exception as e:
            print(f"Error using item: {e}")
            return
        
        # Handle special effects
        self._process_item_effect(found_item_id, target_str, item)
    
    def _process_item_effect(self, item_id: str, target: str, item: dict):
        """Process special item effects."""
        effects = item.get("effects", {})
        
        # Unlock doors
        for door_id, effect in effects.items():
            if effect == "unlock":
                self.state.unlocked_doors.add(door_id)
                print(f"*Click* The lock disengages.")
        
        # Open containers
        room = self.world.get_room(self.state.current_room)
        if room and "chest" in room:
            chest = room["chest"]
            if item_id == chest.get("requires"):
                self.state.opened_containers.add(chest["id"])
                print("The chest opens, revealing its contents!")
                for contained_id in chest.get("contains", []):
                    contained = self.world.get_item(contained_id)
                    if contained:
                        print(f"  → {contained['name']}")
        
        # Handle healing
        if item.get("consumable"):
            if item.get("heal_amount"):
                self.player.heal(item["heal_amount"])
                self.player.inventory.consume(item_id)
        
        # Handle victory item
        if item.get("is_victory_item"):
            self.state.game_complete = True
    
    def _talk_handler(self, args: list):
        """Handle talking to NPCs."""
        room = self.world.get_room(self.state.current_room)
        if not room:
            return
        
        npc_ids = room.get("npcs", [])
        if not npc_ids:
            print("There's no one here to talk to.")
            return
        
        # Find NPC
        target = " ".join(args).lower() if args else ""
        
        found_npc = None
        for npc_id in npc_ids:
            npc = self.world.get_npc(npc_id)
            if npc:
                if not target or target in npc_id.lower() or target in npc.get("name", "").lower():
                    found_npc = npc
                    break
        
        if not found_npc:
            print(f"You don't see '{target}' to talk to.")
            return
        
        # Get dialogue state
        npc_id = found_npc["id"]
        dialogue_trigger = self.state.npc_dialogue_state.get(npc_id, "first_talk")
        
        # Find matching dialogue
        dialogue_data = None
        for dialogue in found_npc.get("dialogue", []):
            if dialogue.get("trigger") == dialogue_trigger:
                dialogue_data = dialogue
                break
        
        # Fallback to first_talk
        if not dialogue_data:
            for dialogue in found_npc.get("dialogue", []):
                if dialogue.get("trigger") == "first_talk":
                    dialogue_data = dialogue
                    break
        
        if not dialogue_data:
            print(f"{found_npc['name']} has nothing to say.")
            return
        
        # Show dialogue with immersion
        npc_greeting(found_npc['name'])
        print()
        type_text(dialogue_data.get("text", "..."))
        
        # Handle options
        options = dialogue_data.get("options")
        responses = dialogue_data.get("responses")
        
        if options and responses:
            print("\nYou can ask about:")
            for i, opt in enumerate(options):
                print(f"  {i + 1}. {opt}")
            
            # Get player choice via student method
            try:
                choice = self.player.respond_to_npc(options)
                if isinstance(choice, int) and 0 <= choice < len(responses):
                    print()
                    print(responses[choice])
            except Exception as e:
                print(f"(Error in respond_to_npc: {e})")
        
        # Update dialogue state
        self.state.npc_dialogue_state[npc_id] = "after_first"
    
    def _status_handler(self, args: list):
        """Show player status."""
        print(self.player.get_status())
    
    def _save_handler(self, args: list):
        """Save the game."""
        if self.saves.save_game(self.player, self.state.to_dict()):
            print("Game saved.")
        else:
            print("Failed to save game.")
    
    def _load_handler(self, args: list):
        """Load a saved game."""
        self._load_game()
    
    def _load_game(self):
        """Load game implementation."""
        player, engine_state = self.saves.load_game(self.player_class or self._get_player_class())
        
        if player and engine_state:
            self.player = player
            self.state = GameState.from_dict(engine_state)
            print("Game loaded.")
            self._describe_room()
        else:
            print("Could not load game.")
    
    def _get_player_class(self):
        """Get the appropriate player class for loading."""
        try:
            from student.player_types import Brute
            return Brute  # Default to Brute if unknown
        except ImportError:
            return None
    
    def _help_handler(self, args: list):
        """Show help."""
        print("""
╔═══════════════════════════════════════════════════════════════════╗
║                          COMMANDS                                 ║
╠═══════════════════════════════════════════════════════════════════╣
║  look              - Describe the current room                    ║
║  look <thing>      - Examine something closely                    ║
║  north/south/etc   - Move in a direction                          ║
║  take <item>       - Pick up an item                              ║
║  inventory         - Show what you're carrying                    ║
║  use <item>        - Use an item on yourself                      ║
║  use <item> on <X> - Use an item on something                     ║
║  talk <npc>        - Talk to someone                              ║
║  status            - Show your health and stats                   ║
║  save              - Save your game                               ║
║  load              - Load a saved game                            ║
║  help              - Show this help                               ║
║  quit              - Exit the game                                ║
╚═══════════════════════════════════════════════════════════════════╝
        """)
    
    def _quit_handler(self, args: list):
        """Quit the game."""
        print("\nSave before quitting? (yes/no)")
        choice = input("> ").strip().lower()
        if choice in ("yes", "y"):
            self._save_handler([])
        print("\nGoodbye, survivor. The stars await your return.\n")
        self.running = False
    
    def _handle_death(self):
        """Handle player death."""
        death_sequence()
        print()
        print("═" * 60)
        print("                     G A M E   O V E R")
        print("═" * 60)
        type_text_slow("\nYou have fallen. But death is not the end—not here.")
        type_text("The station's emergency systems activate...")
        print()
        
        # Respawn at start with full health
        self.state.current_room = "airlock"
        self.player.health = self.player.max_health
        
        input("Press Enter to continue...")
        self._describe_room()
    
    def _show_victory(self):
        """Show victory screen."""
        print()
        print("=" * 60)
        print("""
    ╔═══════════════════════════════════════════════════════╗
    ║                                                       ║
    ║              V I C T O R Y                            ║
    ║                                                       ║
    ║    You activate the distress beacon.                  ║
    ║                                                       ║
    ║    The signal pulses outward, beyond the station,     ║
    ║    beyond the debris field, into the void. Within     ║
    ║    hours, rescue ships will arrive.                   ║
    ║                                                       ║
    ║    Behind you, SIGMA's voice echoes one last time:    ║
    ║    "Remarkable. Perhaps... I underestimated your      ║
    ║    species after all."                                ║
    ║                                                       ║
    ║    The stars wheel slowly as you wait.                ║
    ║    You survived Sigma-7.                              ║
    ║                                                       ║
    ║    But the artifact... the artifact is still here.    ║
    ║    And soon, others will come looking for it.         ║
    ║                                                       ║
    ╚═══════════════════════════════════════════════════════╝
        """)
        print("=" * 60)
        print("\nThank you for playing Sigma-7 Research Station!")
        print("You have completed the OOP Text Adventure.\n")
        self.running = False
