"""
Command Parser - Tokenises and routes player commands.

Engine-owned. Students do NOT edit this file.
"""


class CommandParser:
    """Parses player input and routes to appropriate handlers."""
    
    # Command synonyms for flexibility
    SYNONYMS = {
        "go": "move",
        "walk": "move",
        "run": "move",
        "n": "north",
        "s": "south",
        "e": "east", 
        "w": "west",
        "u": "up",
        "d": "down",
        "get": "take",
        "grab": "take",
        "pick": "take",
        "pickup": "take",
        "i": "inventory",
        "inv": "inventory",
        "items": "inventory",
        "l": "look",
        "examine": "look",
        "inspect": "look",
        "check": "look",
        "x": "look",
        "speak": "talk",
        "chat": "talk",
        "ask": "talk",
        "fight": "attack",
        "hit": "attack",
        "strike": "attack",
        "q": "quit",
        "exit": "quit",
        "bye": "quit",
        "?": "help",
        "h": "help",
        "stats": "status",
        "hp": "status",
        "health": "status",
    }
    
    # Valid commands
    COMMANDS = {
        "look": "look_handler",
        "move": "move_handler",
        "north": "direction_handler",
        "south": "direction_handler",
        "east": "direction_handler",
        "west": "direction_handler",
        "up": "direction_handler",
        "down": "direction_handler",
        "take": "take_handler",
        "inventory": "inventory_handler",
        "use": "use_handler",
        "talk": "talk_handler",
        "save": "save_handler",
        "load": "load_handler",
        "status": "status_handler",
        "help": "help_handler",
        "quit": "quit_handler",
    }
    
    def __init__(self):
        """Initialize the parser."""
        pass
    
    def parse(self, raw_input: str) -> dict:
        """
        Parse raw player input into a command structure.
        
        Args:
            raw_input: The raw string from the player.
            
        Returns:
            A dict with keys: command, args, raw
        """
        # Clean and tokenise
        cleaned = raw_input.strip().lower()
        if not cleaned:
            return {"command": None, "args": [], "raw": raw_input}
        
        tokens = cleaned.split()
        
        # Get the base command
        base_cmd = tokens[0]
        
        # Apply synonyms
        if base_cmd in self.SYNONYMS:
            base_cmd = self.SYNONYMS[base_cmd]
        
        # Get arguments
        args = tokens[1:] if len(tokens) > 1 else []
        
        # Check if it's a valid command
        if base_cmd not in self.COMMANDS:
            return {"command": "unknown", "args": [base_cmd] + args, "raw": raw_input}
        
        return {"command": base_cmd, "args": args, "raw": raw_input}
    
    def get_handler_name(self, command: str) -> str:
        """Get the handler method name for a command."""
        return self.COMMANDS.get(command)
    
    def is_direction(self, word: str) -> bool:
        """Check if a word is a direction."""
        directions = {"north", "south", "east", "west", "up", "down"}
        word = word.lower()
        if word in directions:
            return True
        if word in self.SYNONYMS and self.SYNONYMS[word] in directions:
            return True
        return False
    
    def normalise_direction(self, word: str) -> str:
        """Convert direction synonyms to standard form."""
        word = word.lower()
        if word in self.SYNONYMS:
            return self.SYNONYMS[word]
        return word
    
    @staticmethod
    def join_args(args: list, start: int = 0) -> str:
        """Join arguments back into a string."""
        return " ".join(args[start:])
    
    @staticmethod
    def parse_use_command(args: list) -> tuple:
        """
        Parse 'use X on Y' style commands.
        
        Returns:
            Tuple of (item, target) or (item, None)
        """
        if not args:
            return (None, None)
        
        # Look for 'on' keyword
        try:
            on_index = args.index("on")
            item = " ".join(args[:on_index])
            target = " ".join(args[on_index + 1:])
            return (item, target)
        except ValueError:
            # No 'on' keyword - using on self
            item = " ".join(args)
            return (item, "self")
