"""
Immersion utilities for enhanced Sigma-7 gameplay.

Engine-owned. Students do NOT edit this file.
No dependencies on student code.
"""

import time
import sys
import random


# ============================================================================
# TEXT EFFECTS
# ============================================================================

def type_text(text, delay=0.02):
    """Print text with typewriter effect."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def type_text_slow(text, delay=0.04):
    """Slower typewriter for dramatic moments."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def type_text_fast(text, delay=0.01):
    """Faster typewriter for dialogue."""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


def dramatic_pause(seconds=1.0):
    """Pause for dramatic effect."""
    time.sleep(seconds)


def suspense_dots(count=3, delay=0.5):
    """Show suspenseful dots."""
    for _ in range(count):
        print(".", end='', flush=True)
        time.sleep(delay)
    print()


# ============================================================================
# DISPLAY ELEMENTS
# ============================================================================

def show_divider(char="-", width=60):
    """Print a divider line."""
    print(char * width)


def show_immersive_header(title, subtitle=None):
    """Print an atmospheric styled header."""
    print()
    print("═" * 60)
    print(f"  ▸ {title}")
    if subtitle:
        print(f"    {subtitle}")
    print("═" * 60)


def flicker_text(text, flickers=2):
    """Simulate flickering display."""
    for _ in range(flickers):
        print(f"\r{text}", end='', flush=True)
        time.sleep(0.1)
        print(f"\r{' ' * len(text)}", end='', flush=True)
        time.sleep(0.05)
    print(f"\r{text}")


# ============================================================================
# NARRATIVE FLAVOR
# ============================================================================

AMBIENT_SOUNDS = [
    "A distant hum reverberates through the walls...",
    "Metal groans somewhere in the station's depths.",
    "The ventilation system wheezes, then falls silent.",
    "A light flickers overhead.",
    "Static crackles from a broken speaker.",
    "Your footsteps echo in the emptiness.",
    "Something drips in the distance.",
]

def ambient_flavor():
    """Occasionally add ambient atmosphere (20% chance)."""
    if random.random() < 0.2:
        sound = random.choice(AMBIENT_SOUNDS)
        print()
        type_text_fast(f"  [{sound}]")


def movement_narration(direction):
    """Add flavor to movement."""
    phrases = {
        "north": "You head deeper into the station...",
        "south": "You retrace your steps southward...",
        "east": "You move cautiously to the east...",
        "west": "You make your way west...",
        "up": "You climb upward...",
        "down": "You descend carefully...",
    }
    phrase = phrases.get(direction, f"You move {direction}...")
    type_text_fast(phrase)
    dramatic_pause(0.3)


def combat_start_narration(enemy_name):
    """Dramatic combat encounter start."""
    print()
    show_divider("═")
    type_text_slow(f"  ⚔️  ENCOUNTER: {enemy_name.upper()}")
    show_divider("═")
    dramatic_pause(0.5)


def combat_hit_narration(attacker, target, damage):
    """Flavor for successful attacks."""
    phrases = [
        f"{attacker} strikes {target} for {damage} damage!",
        f"A solid hit! {target} takes {damage} damage.",
        f"{attacker}'s attack connects — {damage} damage!",
    ]
    type_text(random.choice(phrases))


def combat_miss_narration(attacker):
    """Flavor for missed attacks."""
    phrases = [
        f"{attacker}'s attack goes wide!",
        f"A miss! {attacker} whiffs.",
        f"{attacker} swings but connects with nothing.",
    ]
    type_text(random.choice(phrases))


def death_sequence():
    """Dramatic death sequence."""
    print()
    dramatic_pause(0.5)
    type_text_slow("Your vision blurs...")
    dramatic_pause(0.8)
    type_text_slow("The cold of the station seeps into your bones...")
    dramatic_pause(0.8)
    print()
    flicker_text("SYSTEM REBOOT INITIATED", flickers=3)
    dramatic_pause(1.0)


def npc_greeting(npc_name):
    """Atmospheric NPC greeting."""
    dramatic_pause(0.3)
    type_text(f'{npc_name} turns to face you...')
    dramatic_pause(0.5)


def item_pickup_narration(item_name):
    """Flavor for picking up items."""
    phrases = [
        f"You pocket the {item_name}.",
        f"The {item_name} goes into your pack.",
        f"You secure the {item_name} in your inventory.",
    ]
    type_text_fast(random.choice(phrases))


def room_atmosphere(room_name, first_visit=True):
    """Add atmosphere when entering rooms."""
    if first_visit:
        dramatic_pause(0.3)
    ambient_flavor()
